---
title: "Exploratory Data Analysis"
author: "Nikita Sharma"
date: "2024-11-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# libraries
library(arrow)
library(tidyverse)
library(data.table)
```

```{r}
# static house data
static_house_data <- read_parquet("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/static_house_info.parquet")
```

Splitting data among team

```{r}
# Batu
# filtering only houses built in the 1960s and 1970s
houses_60s_70s = static_house_data %>% filter(in.vintage %in% c('1960s', '1970s'))
glimpse(houses_60s_70s)

# Nikita
# filtering only houses built in the 1980s and 1990s
houses_80s_90s = static_house_data %>% filter(in.vintage %in% c('1980s', '1990s'))
glimpse(houses_80s_90s)

# Alice
# filtering only houses built in the 2000s and 2010s
houses_00s_10s = static_house_data %>% filter(in.vintage %in% c('2000s', '2010s'))
glimpse(houses_00s_10s)
```

Combining with energy data for 80s-90s

```{r}
# Empty variable for storing combined energy data
energy_combined = NULL

# Iterate over each building ID 
for (building_id in houses_80s_90s$bldg_id) {
  # Construct URL to fetch energy data for each building
  energy_data_url = paste0("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/2023-houseData/", building_id, ".parquet")
  building_energy = read_parquet(energy_data_url)
  building_energy$building_id = building_id

  
  energy_combined = if (is.null(energy_combined)) building_energy else rbind(energy_combined, building_energy)
  break
}

energy_house_data = left_join(energy_combined, houses_80s_90s, by = c('building_id' = 'bldg_id'))

energy_house_data$time = as.POSIXct(energy_house_data$time, "%Y-%m-%d %H:%M:%S", tz = "UTC")

```

Combining with weather data for 80s to 90s

```{r}
unique_counties = unique(energy_house_data$in.county)
# Empty variable for storing combined weather data
weather_combined = NULL

# Iterate over counties
for (county_id in unique_counties) {
  # Construct URL
  weather_data_url = paste0("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/weather/2023-weather-data/", county_id, ".csv")
  county_weather = read_csv(weather_data_url)
  county_weather$in.county = county_id

  weather_combined = if (is.null(weather_combined)) county_weather else rbind(weather_combined, county_weather)
  break
}

# Date time formatting
weather_combined$date_time = as.POSIXct(weather_combined$date_time, "%Y-%m-%d %H:%M:%S", tz = "UTC")

# Convert data frames to data tables
setDT(energy_house_data)
setDT(weather_combined)

# Merge energy house data with weather data
final_data = merge(energy_house_data, weather_combined, 
                   by.x = c("in.county", "time"), 
                   by.y = c("in.county", "date_time"), all.x = TRUE)
```